services:
  vpn:
    container_name: vpn
    image: 'dperson/openvpn-client:latest'
    environment:
      - 'OTHER_ARGS= --mute-replay-warnings'
    cap_add:
      - net_admin
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - '${ROOT}/MediaCenter/config/vpn:/vpn'
      - /lib/modules:/lib/modules
    security_opt:
      - 'label:disable'
    devices:
      - '/dev/net/tun:/dev/net/tun'
    ports:
      - '8080:8080' # qBittorrent Web UI port
    command: '-f "" -r ${LAN_NETWORK}'

  qbittorrent:
    container_name: qbittorrent
    image: 'lscr.io/linuxserver/qbittorrent:latest'
    restart: unless-stopped
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
      - 'WEBUI_PORT=8080'
    volumes:
      - '${ROOT}/MediaCenter/config/qbittorrent:/config'
      - '${HDDSTORAGE}:/MediaCenterBox'
    network_mode: 'service:vpn'
    depends_on:
      - vpn

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '${ROOT}/MediaCenter/config/prowlarr:/config'
    restart: unless-stopped
    ports:
      - '9696:9696'

  sonarr:
    container_name: sonarr
    image: 'lscr.io/linuxserver/sonarr:latest'
    restart: unless-stopped
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${ROOT}/MediaCenter/config/sonarr:/config'
      - '${HDDSTORAGE}:/MediaCenterBox'
    ports:
      - '8989:8989'

  radarr:
    container_name: radarr
    image: 'lscr.io/linuxserver/radarr:latest'
    restart: unless-stopped
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${ROOT}/MediaCenter/config/radarr:/config'
      - '${HDDSTORAGE}:/MediaCenterBox'
    ports:
      - '7878:7878'

  lidarr:
    container_name: lidarr
    image: 'lscr.io/linuxserver/lidarr:latest'
    restart: unless-stopped
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${ROOT}/MediaCenter/config/lidarr:/config'
      - '${HDDSTORAGE}:/MediaCenterBox'
    ports:
      - '8686:8686'
      
  bazarr:
    container_name: bazarr
    image: 'lscr.io/linuxserver/bazarr:latest'
    restart: unless-stopped
    #network_mode: host
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
      - UMASK_SET=022
    volumes:
      - '${ROOT}/MediaCenter/config/bazarr:/config'
      - '${HDDSTORAGE}:/MediaCenterBox'
    ports:
      - '6767:6767'
      
  jellyfin:
    container_name: jellyfin
    image: 'lscr.io/linuxserver/jellyfin:latest'
    restart: unless-stopped
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '${ROOT}/MediaCenter/config/jellyfin:/config'
      - '${HDDSTORAGE}/Completed:/MediaCenterBox'
    ports:
      - '8096:8096'

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - 'LOG_LEVEL=info'
      - 'LOG_HTML=false'
      - 'CAPTCHA_SOLVER=none'
      - 'TZ=${TZ}'
    ports:
      - '8191:8191'
    restart: unless-stopped


### Optional Containers

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    environment:
      - LOG_LEVEL=info
      - 'TZ=${TZ}'
    ports:
      - '5055:5055'
    volumes:
      - '${ROOT}/MediaCenter/config/seerr:/app/config'
    restart: unless-stopped

  musicseerr:
    image: ghcr.io/habirabbu/musicseerr:latest
    container_name: musicseerr
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'PORT=8688'
      - 'TZ=${TZ}'
    ports:
      - '8688:8688'
    volumes:
      - '${ROOT}/MediaCenter/config/musicseerr:/app/config'
      - '${ROOT}/MediaCenter/config/musicseerr-cache:/app/cache'
      - '${HDDSTORAGE}/Completed/Music:/music:ro'
    restart: unless-stopped
